### ISSUE TITLE
Ajouter le fichier README.md 

### ISSUE THREAD

**Issue by jpainam** [Nodjinar/Code-Booki#1]
Avant de jeter un coup d'oeil dans ton projet, peux-tu ajouter un fichier `README.md` contenant la description de ton projet et tout autre information nécessaire.

**Comment by Nodjinar** [comment]
Bonjour Mr Jean Paul, comment vous allez? j'ai fait le travail demandé, vous pouvez verifiés. Merci

**Comment by jpainam** [comment]
D'accord. je vais jeter un coup d'oeil.

Merci

**Comment by Nodjinar** [comment]
Bonsoir Mr Jean-Paul, comment allez vous ?. Je vous présente
* mes vœux de santé et de bonheur pour cette nouvelle année 2023. Je vous
souhaite le meilleur, ainsi qu'à vos proches et une pleine réussite
professionnelle.*
*bonne année*
*cordialement.*

Le ven. 9 déc. 2022 à 16:14, Jean-Paul Ainam ***@***.***> a
écrit :

> Bonjour.
> Une fois que tu ai résolu le problème. Pas besoin d’envoyer un e-mail.
> Il faut juste commenter en dessous de l’Issue et indiquer la solution
> apportée.
> Je serai notifié directement et je vais marquer le issue comme résolue.
>
> Merci
>

**Comment by jpainam** [comment]
Merci. Bonne et heureuse année 2023 👍
